revert: remove TLS client cert config due to maddy v0.8.1 bug
The official maddy v0.8.1 image has a reflection bug when using
tls_client configuration, causing panic on startup. Reverting to
IP allowlist authentication which is working reliably.

Error: panic: reflect.Set: value of type *tls.Config is not assignable to type tls.Config